export const TaskActionsTypes = {
    // FETCH TASK FROM DB (REDUX SAGA)
    FETCH_TASKS_START: 'FETCH_TASK_START',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILURE: 'FETCH_TASKS_FAILURE',

    // ADD TASK TO DB
    ADD_TASK_START: 'ADD_TASK_START',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

    // REMOVE TASK FROM DB
    REMOVE_TASK_START: 'REMOVE_TASK_START',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
    REMOVE_TASK_FAILURE: 'REMOVE_TASK_FAILURE',

    // EDIT TASK
    EDIT_TASK_START: 'EDIT_TASK_START',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAILURE: 'EDIT_TASK_FAILURE',
}